=== gonellat/TestBDDFramework/src/test/resources/data/scenariodatavalidation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="scenariodata">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="signuppage">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name = "name" type = "xs:string"/>
                     <xs:element name = "emailaddress" type = "xs:string"/>
                  </xs:sequence>
                </xs:complexType>
            </xs:element>
             <xs:element name="accountinfopage">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name = "firstname" type = "xs:string"/>
                     <xs:element name = "lastname" type = "xs:string"/>
                     <xs:element name = "company" type = "xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== gonellat/TestBDDFramework/src/test/resources/data/WebFeatureScenario2b.xml
<?xml version="1.0"?>
<scenariodata
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="scenariodatavalidation.xsd">

   <signuppage>
      <name>automationTest</name>
      <emailaddress>automationTest@hotmail.com</emailaddress>
    </signuppage>
    <accountinfopage>
      <firstname>Tim</firstname>
      <lastname>Gonella</lastname>
      <company></company>
    </accountinfopage>
</scenariodata>
